#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ntfs-3g
Version  : 3g.progs.2017.3.23
Release  : 11
URL      : https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2017.3.23.tgz
Source0  : https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2017.3.23.tgz
Summary  : NTFS-3G Read/Write Driver Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: ntfs-3g-bin
Requires: ntfs-3g-lib
Requires: ntfs-3g-doc
BuildRequires : glibc-staticdev
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(uuid)
BuildRequires : util-linux-dev

%description
INTRODUCTION
============
The NTFS-3G driver is an open source, freely available read/write NTFS driver
for Linux, FreeBSD, Mac OS X, NetBSD, OpenSolaris, QNX and Haiku. It provides
safe and fast handling of the Windows XP, Windows Server 2003, Windows 2000,
Windows Vista, Windows Server 2008 and Windows 7 file systems.

%package bin
Summary: bin components for the ntfs-3g package.
Group: Binaries

%description bin
bin components for the ntfs-3g package.


%package dev
Summary: dev components for the ntfs-3g package.
Group: Development
Requires: ntfs-3g-lib
Requires: ntfs-3g-bin
Provides: ntfs-3g-devel

%description dev
dev components for the ntfs-3g package.


%package doc
Summary: doc components for the ntfs-3g package.
Group: Documentation

%description doc
doc components for the ntfs-3g package.


%package lib
Summary: lib components for the ntfs-3g package.
Group: Libraries

%description lib
lib components for the ntfs-3g package.


%prep
%setup -q -n ntfs-3g_ntfsprogs-2017.3.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523377921
%configure --disable-static --disable-ldconfig
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1523377921
rm -rf %{buildroot}
%make_install
## make_install_append content
ln -sf /usr/bin/mount.ntfs-3g %{buildroot}/usr/bin/mount.ntfs
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lowntfs-3g
/usr/bin/mkfs.ntfs
/usr/bin/mkntfs
/usr/bin/mount.lowntfs-3g
/usr/bin/mount.ntfs
/usr/bin/mount.ntfs-3g
/usr/bin/ntfs-3g
/usr/bin/ntfs-3g.probe
/usr/bin/ntfscat
/usr/bin/ntfsclone
/usr/bin/ntfscluster
/usr/bin/ntfscmp
/usr/bin/ntfscp
/usr/bin/ntfsfix
/usr/bin/ntfsinfo
/usr/bin/ntfslabel
/usr/bin/ntfsls
/usr/bin/ntfsresize
/usr/bin/ntfsundelete

%files dev
%defattr(-,root,root,-)
/usr/include/ntfs-3g/acls.h
/usr/include/ntfs-3g/attrib.h
/usr/include/ntfs-3g/attrlist.h
/usr/include/ntfs-3g/bitmap.h
/usr/include/ntfs-3g/bootsect.h
/usr/include/ntfs-3g/cache.h
/usr/include/ntfs-3g/collate.h
/usr/include/ntfs-3g/compat.h
/usr/include/ntfs-3g/compress.h
/usr/include/ntfs-3g/debug.h
/usr/include/ntfs-3g/device.h
/usr/include/ntfs-3g/device_io.h
/usr/include/ntfs-3g/dir.h
/usr/include/ntfs-3g/ea.h
/usr/include/ntfs-3g/efs.h
/usr/include/ntfs-3g/endians.h
/usr/include/ntfs-3g/index.h
/usr/include/ntfs-3g/inode.h
/usr/include/ntfs-3g/ioctl.h
/usr/include/ntfs-3g/layout.h
/usr/include/ntfs-3g/lcnalloc.h
/usr/include/ntfs-3g/logfile.h
/usr/include/ntfs-3g/logging.h
/usr/include/ntfs-3g/mft.h
/usr/include/ntfs-3g/misc.h
/usr/include/ntfs-3g/mst.h
/usr/include/ntfs-3g/ntfstime.h
/usr/include/ntfs-3g/object_id.h
/usr/include/ntfs-3g/param.h
/usr/include/ntfs-3g/plugin.h
/usr/include/ntfs-3g/realpath.h
/usr/include/ntfs-3g/reparse.h
/usr/include/ntfs-3g/runlist.h
/usr/include/ntfs-3g/security.h
/usr/include/ntfs-3g/support.h
/usr/include/ntfs-3g/types.h
/usr/include/ntfs-3g/unistr.h
/usr/include/ntfs-3g/volume.h
/usr/include/ntfs-3g/xattrs.h
/usr/lib64/libntfs-3g.so
/usr/lib64/pkgconfig/libntfs-3g.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/ntfs\-3g/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libntfs-3g.so.88
/usr/lib64/libntfs-3g.so.88.0.0
