#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ntfs-3g
Version  : _ntfsprogs
Release  : 2
URL      : https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2016.2.22.tgz
Source0  : https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2016.2.22.tgz
Summary  : NTFS-3G Read/Write Driver Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: ntfs-3g-bin
Requires: ntfs-3g-lib
Requires: ntfs-3g-doc
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(uuid)
BuildRequires : util-linux-dev

%description
INTRODUCTION
============
The NTFS-3G driver is an open source, freely available read/write NTFS driver
for Linux, FreeBSD, Mac OS X, NetBSD, OpenSolaris, QNX and Haiku. It provides
safe and fast handling of the Windows XP, Windows Server 2003, Windows 2000,
Windows Vista, Windows Server 2008 and Windows 7 file systems.

%package bin
Summary: bin components for the ntfs-3g package.
Group: Binaries

%description bin
bin components for the ntfs-3g package.


%package dev
Summary: dev components for the ntfs-3g package.
Group: Development
Requires: ntfs-3g-lib
Requires: ntfs-3g-bin
Provides: ntfs-3g-devel

%description dev
dev components for the ntfs-3g package.


%package doc
Summary: doc components for the ntfs-3g package.
Group: Documentation

%description doc
doc components for the ntfs-3g package.


%package lib
Summary: lib components for the ntfs-3g package.
Group: Libraries

%description lib
lib components for the ntfs-3g package.


%prep
%setup -q -n ntfs-3g_ntfsprogs-2016.2.22

%build
export LANG=C
%configure --disable-static --disable-ldconfig
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lowntfs-3g
/usr/bin/mkfs.ntfs
/usr/bin/mkntfs
/usr/bin/mount.lowntfs-3g
/usr/bin/mount.ntfs-3g
/usr/bin/ntfs-3g
/usr/bin/ntfs-3g.probe
/usr/bin/ntfs-3g.secaudit
/usr/bin/ntfs-3g.usermap
/usr/bin/ntfscat
/usr/bin/ntfsclone
/usr/bin/ntfscluster
/usr/bin/ntfscmp
/usr/bin/ntfscp
/usr/bin/ntfsfix
/usr/bin/ntfsinfo
/usr/bin/ntfslabel
/usr/bin/ntfsls
/usr/bin/ntfsresize
/usr/bin/ntfsundelete

%files dev
%defattr(-,root,root,-)
/usr/include/ntfs-3g/acls.h
/usr/include/ntfs-3g/attrib.h
/usr/include/ntfs-3g/attrlist.h
/usr/include/ntfs-3g/bitmap.h
/usr/include/ntfs-3g/bootsect.h
/usr/include/ntfs-3g/cache.h
/usr/include/ntfs-3g/collate.h
/usr/include/ntfs-3g/compat.h
/usr/include/ntfs-3g/compress.h
/usr/include/ntfs-3g/debug.h
/usr/include/ntfs-3g/device.h
/usr/include/ntfs-3g/device_io.h
/usr/include/ntfs-3g/dir.h
/usr/include/ntfs-3g/ea.h
/usr/include/ntfs-3g/efs.h
/usr/include/ntfs-3g/endians.h
/usr/include/ntfs-3g/index.h
/usr/include/ntfs-3g/inode.h
/usr/include/ntfs-3g/ioctl.h
/usr/include/ntfs-3g/layout.h
/usr/include/ntfs-3g/lcnalloc.h
/usr/include/ntfs-3g/logfile.h
/usr/include/ntfs-3g/logging.h
/usr/include/ntfs-3g/mft.h
/usr/include/ntfs-3g/misc.h
/usr/include/ntfs-3g/mst.h
/usr/include/ntfs-3g/ntfstime.h
/usr/include/ntfs-3g/object_id.h
/usr/include/ntfs-3g/param.h
/usr/include/ntfs-3g/realpath.h
/usr/include/ntfs-3g/reparse.h
/usr/include/ntfs-3g/runlist.h
/usr/include/ntfs-3g/security.h
/usr/include/ntfs-3g/support.h
/usr/include/ntfs-3g/types.h
/usr/include/ntfs-3g/unistr.h
/usr/include/ntfs-3g/volume.h
/usr/include/ntfs-3g/xattrs.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/ntfs-3g/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
